---
# https://taskfile.dev

version: '3'

tasks:

  update:
    desc: Install/Update Ansible and Python packages
    cmds:
      - pip3 install --require-virtualenv --upgrade pip setuptools
      - pip3 install --require-virtualenv --upgrade -r requirements.txt

...
